global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "nodeapp"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "expressapp"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]